version: "3.7"

volumes:
  db-data:

services:
  web:
    image: node:12-alpine
    working_dir: /home/node/app/backend
    command: npm start
    volumes:
      - ./backend:/home/node/app/backend
      - ./frontend:/home/node/app/frontend
    ports:
      - 80:3000

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: lntsunday
      POSTGRES_PASSWORD: lineate4@Sun
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ops/db-backups:/backup
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
